version: '3.9'

services:

  nginx:
    image: nginx:alpine
    environment:
      frontend_domain: frontend.local
      backend_domain: backend.local
    ports:
      - 80:80
    networks:
      - "apple_network"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./frontend/web:/app/frontend/web
      - ./backend/web:/app/backend/web

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/app
    networks:
      - apple_network
      - db # Connect tou your database

networks:
  apple_network:
    external: false
  db:
    external: true